import os

configfile: os.path.join(workflow.basedir, "..", "config", "config.yaml")

include: os.path.join(workflow.basedir, "rules", "preflight.smk")
include: os.path.join(workflow.basedir,"rules","fastq_preprocess.smk")


rule all:
    input:
        # targets["raw"], # No longer need these
        targets["trimmed"]