# ============================================================================
# Snakemake SLURM profile for Singularity (E.g. in Pawsey Setonix)
# ============================================================================
#
# Usage:
#   snakemake --workflow-profile config/slurm_singularity
# ============================================================================

executor: slurm
jobs: 100
use-singularity: true
use-conda: false
latency-wait: 120
restart-times: 1

# Bind-mount /scratch and /software so containers can see data and databases
singularity-args: "-B /scratch -B /software"

# SLURM defaults
default-resources:
  - "slurm_account=your_acc_name_or_project"
  - "slurm_partition=work"
  - "mem_mb=32000"
  - "runtime=480"
  - "disk_mb=0"

# Limit heavy jobs
set-resources:
  - "remove_human_reads:jobs=95"
  #- "metaphlan:jobs=30"
  #- "singlem:jobs=30"
  #- "metaspades:jobs=15"
  #- "metaspades:runtime=2880"           # 48 hours - adjust as required
  #- "metaspades:slurm_partition=long"   # Use long partition for assembly - adjust partition as requried
  #- "humann:jobs=20"
  #- "antismash_contigs:jobs=15"
  #- "antismash_contigs:runtime=2800"    # reduce runtime or change partition
  #- "antismash_contigs:slurm_partition=long"
  #- "rgi:jobs=15"
  #- "rgi:slurm_partition=long"