title: OpusTaxa
description: A comprehensive Snakemake pipeline for end-to-end metagenomic analysis
baseurl: "/OpusTaxa"
url: "https://yenkaic.github.io"

remote_theme: just-the-docs/just-the-docs@v0.10.0

color_scheme: light

# Search
search_enabled: true
search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false

# Aux links in top-right
aux_links:
  "GitHub":
    - "https://github.com/yenkaiC/OpusTaxa"

aux_links_new_tab: true

# Navigation
nav_sort: order

# Footer content
footer_content: "OpusTaxa &mdash; MIT License. Questions? Open an issue on GitHub."

# Callout
callouts_level: quiet
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red

# Plugins
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - "*.gemspec"
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
